// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0H9g_1HA_vAavkJO2W8M0F3IEN7nVrRY',
    appId: '1:853373536187:web:5cf36118ff0d0d25d9669e',
    messagingSenderId: '853373536187',
    projectId: 'flutter-instagram-420f1',
    authDomain: 'flutter-instagram-420f1.firebaseapp.com',
    storageBucket: 'flutter-instagram-420f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmttIVJbMzX6V-QVHAr2EOkJofkSIUdYc',
    appId: '1:853373536187:android:23baecdb4db13051d9669e',
    messagingSenderId: '853373536187',
    projectId: 'flutter-instagram-420f1',
    storageBucket: 'flutter-instagram-420f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlLINUvvkmLBnyLSKJqpeBuSlv58HNw4',
    appId: '1:853373536187:ios:b65276d86a6e598cd9669e',
    messagingSenderId: '853373536187',
    projectId: 'flutter-instagram-420f1',
    storageBucket: 'flutter-instagram-420f1.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAlLINUvvkmLBnyLSKJqpeBuSlv58HNw4',
    appId: '1:853373536187:ios:b65276d86a6e598cd9669e',
    messagingSenderId: '853373536187',
    projectId: 'flutter-instagram-420f1',
    storageBucket: 'flutter-instagram-420f1.firebasestorage.app',
    iosBundleId: 'com.example.flutterInstagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0H9g_1HA_vAavkJO2W8M0F3IEN7nVrRY',
    appId: '1:853373536187:web:2544e5a04cc515c7d9669e',
    messagingSenderId: '853373536187',
    projectId: 'flutter-instagram-420f1',
    authDomain: 'flutter-instagram-420f1.firebaseapp.com',
    storageBucket: 'flutter-instagram-420f1.firebasestorage.app',
  );
}
